import { createFileRoute } from "@tanstack/react-router";
import { CheckCircle2, Mail, MapPin, Phone, Send } from "lucide-react";
import { FormEvent, useState } from "react";
import { useServerFn } from "@tanstack/react-start";
import { PageHero } from "@/components/page";
import { Button } from "@/components/ui/button";
import { modules } from "@/content/site";
import { submitDemoRequest } from "@/lib/demo-request.functions";

export const Route=createFileRoute("/contact")({head:()=>({meta:[{title:"Request a Demo — SafeNexG"},{name:"description",content:"Request a tailored SafeNexG EHS software demo for your industrial plant or safety team."},{property:"og:title",content:"Request a SafeNexG Demo"},{property:"og:description",content:"See how SafeNexG can digitise your plant's safety workflows."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:"/contact"}]}),component:Contact});
type Data={name:string;company:string;designation:string;workEmail:string;phone:string;plantSize:"<100"|"100–500"|"500–2000"|"2000+ employees"|"";message:string};
const initial:Data={name:"",company:"",designation:"",workEmail:"",phone:"",plantSize:"",message:""};
function Contact(){const submit=useServerFn(submitDemoRequest);const [data,setData]=useState(initial);const [selected,setSelected]=useState<string[]>([]);const [status,setStatus]=useState<"idle"|"sending"|"done"|"error">("idle");const [error,setError]=useState("");
 const set=(key:keyof Data,value:string)=>setData(v=>({...v,[key]:value}));const toggle=(name:string)=>setSelected(s=>s.includes(name)?s.filter(x=>x!==name):[...s,name]);
 async function onSubmit(e:FormEvent){e.preventDefault();setError("");if(!data.plantSize||selected.length===0){setError("Please select your plant size and at least one module.");return}setStatus("sending");try{await submit({data:{...data,plantSize:data.plantSize,modules:selected}});setStatus("done");setData(initial);setSelected([])}catch{setStatus("error");setError("We couldn't save your request. Please try again.")}}
 return <><PageHero eyebrow="Request a demo" title="See SafeNexG around your plant's priorities." description="Tell us about your operation and the modules you want to explore. We will use this information to prepare a relevant walkthrough."/><section className="section"><div className="container contact-layout"><div className="contact-panel"><span className="eyebrow">Start a conversation</span><h2>Bring your current safety workflow.</h2><p>We can focus the demonstration on the processes, roles and reporting needs that matter to your team.</p><div className="contact-details"><span><Phone/>[Phone number]</span><span><Mail/>[Email]</span><span><MapPin/>[Company address]</span></div><div className="map-placeholder"><MapPin/><span>[Map / office location]</span></div></div><div className="form-wrap">{status==="done"?<div className="success-state"><CheckCircle2/><h2>Thank you. Your request is saved.</h2><p>Our team can review the details you submitted and follow up using your work contact information.</p><Button onClick={()=>setStatus("idle")}>Send another request</Button></div>:<form onSubmit={onSubmit} noValidate><div className="form-grid"><Field label="Name" value={data.name} onChange={v=>set("name",v)} required minLength={2} maxLength={100}/><Field label="Company" value={data.company} onChange={v=>set("company",v)} required minLength={2} maxLength={150}/><Field label="Designation" value={data.designation} onChange={v=>set("designation",v)} required minLength={2} maxLength={100}/><Field label="Work email" type="email" value={data.workEmail} onChange={v=>set("workEmail",v)} required maxLength={255}/><Field label="Phone" type="tel" value={data.phone} onChange={v=>set("phone",v)} required minLength={7} maxLength={30}/><label><span>Plant size</span><select value={data.plantSize} onChange={e=>set("plantSize",e.target.value)} required><option value="">Select plant size</option><option>&lt;100</option><option>100–500</option><option>500–2000</option><option>2000+ employees</option></select></label></div><fieldset><legend>Modules of interest</legend><div className="chip-list">{modules.map(m=><button type="button" key={m.title} className={selected.includes(m.title)?"chip selected":"chip"} aria-pressed={selected.includes(m.title)} onClick={()=>toggle(m.title)}>{m.title}</button>)}</div></fieldset><label><span>Message</span><textarea rows={5} maxLength={2000} value={data.message} onChange={e=>set("message",e.target.value)} placeholder="Tell us about your current priorities or processes."/></label>{error&&<p className="form-error" role="alert">{error}</p>}<Button type="submit" size="lg" disabled={status==="sending"}>{status==="sending"?"Saving request…":<>Request my demo <Send/></>}</Button><p className="form-note">Your details are used only to respond to this demo request.</p></form>}</div></div></section></>}
function Field({label,value,onChange,type="text",...props}:{label:string;value:string;onChange:(v:string)=>void;type?:string;required?:boolean;minLength?:number;maxLength?:number}){return <label><span>{label}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)} {...props}/></label>}
