import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, CheckCircle2, FileCheck2, LayoutDashboard, ShieldCheck } from "lucide-react";
import { motion, useReducedMotion } from "motion/react";
import { Button } from "@/components/ui/button";
import { HeroDashboard } from "@/components/hero-dashboard";
import { CtaBand, SectionHeading } from "@/components/page";
import { Reveal } from "@/components/reveal";
import { capabilities, industries, modules } from "@/content/site";

export const Route=createFileRoute("/")({head:()=>({meta:[{title:"SafeNexG — Online Safety Management System"},{name:"description",content:"Digital EHS software for audits, permits, incidents, occupational health, training and fire safety in Indian industrial plants."},{property:"og:title",content:"SafeNexG — Online Safety Management System"},{property:"og:description",content:"One auditable platform for safety management across the shop floor and boardroom."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:"/"}]}),component:Home});
function Home(){const reduce=useReducedMotion();const heroVisualMotion=reduce?{}:{animate:{y:[0,-10,0]},transition:{duration:6,repeat:Infinity,ease:"easeInOut" as const}};return <>
<section className="home-hero"><div className="hero-grid container"><div className="hero-copy"><motion.span className="eyebrow eyebrow-dark" initial={reduce?false:{opacity:0,y:12}} animate={{opacity:1,y:0}}>Online Safety Management System</motion.span><h1>{["Zero","Accident.","One","Platform."].map((w,i)=><motion.span key={w} initial={reduce?false:{opacity:0,y:28}} animate={{opacity:1,y:0}} transition={{delay:.08*i,duration:.5}}>{w} </motion.span>)}</h1><motion.p initial={reduce?false:{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{delay:.4}}>A single platform for audits, permits, incidents, training, occupational health and fire safety — built for the shop floor and the boardroom.</motion.p><motion.div className="hero-actions" initial={reduce?false:{opacity:0}} animate={{opacity:1}} transition={{delay:.55}}><Button asChild size="lg"><Link to="/contact">Request a Free Demo <ArrowRight/></Link></Button><Button asChild size="lg" variant="outlineDark"><Link to="/solutions">Explore Modules</Link></Button></motion.div><div className="hero-proof"><ShieldCheck/><span>Auditable workflows</span><span>•</span><span>Mobile + QR ready</span></div></div><motion.div className="hero-visual" initial={reduce?false:{opacity:0,x:60,scale:.94}} animate={{opacity:1,x:0,scale:1}} transition={{duration:.9,delay:.3,ease:[.2,.8,.2,1]}}><motion.div {...heroVisualMotion}><div className="visual-glow"/><HeroDashboard/><motion.div className="floating-status" initial={reduce?false:{opacity:0,y:16,scale:.9}} animate={{opacity:1,y:0,scale:1}} transition={{duration:.5,delay:1,ease:[.2,.8,.2,1]}}><CheckCircle2/><span><b>Actions visible</b><small>From report to closure</small></span></motion.div></motion.div></motion.div></div></section>
<section className="trust-band"><div className="container"><span className="trust-label">Built for</span><div className="industry-strip">{industries.map(({name,icon:Icon})=><span key={name}><Icon/>{name}</span>)}</div><div className="logo-placeholder">[Client logos to be added]</div></div></section>
<section className="section"><div className="container problem-grid"><Reveal><span className="eyebrow">One source of truth</span><h2>Safety work should not disappear between systems.</h2></Reveal><Reveal delay={.1}><p className="lead">Paper registers, Excel sheets and WhatsApp follow-ups miss things. SafeNexG brings every safety process into one auditable system.</p><div className="problem-points"><span><FileCheck2/>Structured records</span><span><LayoutDashboard/>Live visibility</span><span><ShieldCheck/>Clear accountability</span></div></Reveal></div></section>
<section className="section section-muted"><div className="container"><SectionHeading eyebrow="Connected modules" title="Every critical safety process. One operating system." description="Start with the modules your plant needs, then bring more workflows into the same accountable platform."/><div className="module-grid">{modules.slice(0,9).map((m,i)=><Reveal key={m.title} delay={(i%3)*.06} className="module-card"><div className="icon-box"><m.icon/></div><h3>{m.title}</h3><p>{m.short}</p><Link to="/solutions">View capabilities <ArrowRight/></Link></Reveal>)}</div><div className="center-action"><Button asChild variant="outline"><Link to="/solutions">View all 15 solution areas</Link></Button></div></div></section>
<section className="section"><div className="container"><SectionHeading eyebrow="How it works" title="A clear path from field activity to verified closure." center/><div className="timeline">{[["01","Record","Field users log audits, observations, violations, incidents and inspections using mobile and QR."],["02","Review","HODs and the OHC team review, approve or reject, and assign corrective actions."],["03","Close","Actions are tracked to closure with target dates, escalations and a complete audit trail."],["04","Report","Live dashboards, PDF and Excel reports, and expiry alerts keep management informed."]].map(([n,t,d],i)=><Reveal key={n} delay={i*.08} className="timeline-step"><span>{n}</span><h3>{t}</h3><p>{d}</p></Reveal>)}</div></div></section>
<section className="section section-dark"><div className="container"><SectionHeading eyebrow="Platform capabilities" title="Designed for the plant floor. Ready for management review." description="Fast field capture and disciplined governance, without maintaining disconnected tools."/><div className="capability-grid">{capabilities.map((c,i)=><Reveal key={c.title} delay={(i%3)*.07} className="capability-item"><div className="icon-box dark-icon"><c.icon/></div><div><h3>{c.title}</h3><p>{c.text}</p></div></Reveal>)}</div></div></section>
<section className="section"><div className="container benefit-layout"><div><SectionHeading eyebrow="Operational value" title="Less chasing. Better evidence. Safer decisions."/><div className="benefit-list">{["Faster closure of actions","Audit-ready records","Real-time visibility for management","Less paperwork","Compliance tracking and expiry alerts"].map(x=><Reveal key={x} className="benefit"><CheckCircle2/><span>{x}</span></Reveal>)}</div></div><div className="testimonial-wrap"><h3>What clients say</h3><div className="testimonial-card"><span>[Client testimonial]</span><p>[Client name, designation and company to be added]</p></div><div className="testimonial-card"><span>[Client testimonial]</span><p>[Client name, designation and company to be added]</p></div></div></div></section><CtaBand/></>}
