import { Link, useRouterState } from "@tanstack/react-router";
import { Menu, Moon, Phone, Sun, X, Linkedin, Youtube, Instagram } from "lucide-react";
import { useEffect, useState } from "react";
import { BrandLogo } from "./brand-logo";
import { Button } from "./ui/button";
import { nav } from "@/content/site";

export function SiteShell({children}:{children:React.ReactNode}) {
 const [open,setOpen]=useState(false); const [dark,setDark]=useState(false); const path=useRouterState({select:s=>s.location.pathname});
 useEffect(()=>{setDark(document.documentElement.classList.contains("dark"))},[]);
 const toggle=()=>{const next=!dark;setDark(next);document.documentElement.classList.toggle("dark",next);localStorage.setItem("safenexg-theme",next?"dark":"light")};
 useEffect(()=>setOpen(false),[path]);
 useEffect(()=>{if(!open)return;const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape")setOpen(false)};const prev=document.body.style.overflow;document.body.style.overflow="hidden";window.addEventListener("keydown",onKey);return()=>{document.body.style.overflow=prev;window.removeEventListener("keydown",onKey)}},[open]);
 return <div className="site-shell"><header className="site-header"><div className="site-header-inner"><Link to="/" aria-label="SafeNexG home"><BrandLogo/></Link><nav className="desktop-nav" aria-label="Main navigation">{nav.map(n=><Link key={n.to} to={n.to} activeOptions={{exact:n.to==="/"}} activeProps={{className:"nav-link active"}} className="nav-link">{n.label}</Link>)}</nav><div className="nav-actions"><button type="button" className="icon-button" aria-label={`Switch to ${dark?"light":"dark"} theme`} onClick={toggle}>{dark?<Sun/>:<Moon/>}</button><Button asChild className="desktop-demo"><Link to="/contact">Request a Demo</Link></Button><button type="button" className="icon-button mobile-menu-button" aria-label="Open menu" aria-haspopup="dialog" aria-expanded={open} onClick={()=>setOpen(true)}><Menu/></button></div></div></header><div className={`mobile-menu ${open?"open":""}`} inert={!open}><div className="mobile-menu-backdrop" onClick={()=>setOpen(false)}/><div className="mobile-menu-panel" role="dialog" aria-modal="true" aria-label="Main menu"><div className="mobile-menu-head"><BrandLogo/><button type="button" className="icon-button" aria-label="Close menu" onClick={()=>setOpen(false)}><X/></button></div><nav className="mobile-menu-links" aria-label="Mobile navigation">{nav.map((n,i)=><Link key={n.to} to={n.to} style={{"--i":i} as React.CSSProperties} activeOptions={{exact:n.to==="/"}} activeProps={{className:"mobile-nav-link active"}} className="mobile-nav-link" onClick={()=>setOpen(false)}>{n.label}</Link>)}</nav><Button asChild className="mobile-menu-cta"><Link to="/contact" onClick={()=>setOpen(false)}>Request a Demo</Link></Button></div></div><main>{children}</main><Footer/><a className="mobile-call" href="tel:[Phone number]" aria-label="Call SafeNexG"><Phone/><span>Call</span></a></div>
}
function Footer(){return <footer className="site-footer"><div className="container footer-grid"><div><BrandLogo inverse/><p>Web-based EHS management for safer, more accountable industrial operations.</p></div><div><h3>Solutions</h3><Link to="/solutions">EHS modules</Link><Link to="/features">Platform features</Link><Link to="/industries">Industries</Link></div><div><h3>Company</h3><Link to="/about">About SafeNexG</Link><Link to="/contact">Request a demo</Link><span>[Company address]</span></div><div><h3>Contact</h3><span>[Phone number]</span><span>[Email]</span><span>[domain]</span><div className="socials"><a href="[LinkedIn]" aria-label="LinkedIn"><Linkedin/></a><a href="[YouTube]" aria-label="YouTube"><Youtube/></a><a href="[Instagram]" aria-label="Instagram"><Instagram/></a></div></div></div><div className="container footer-bottom"><span>© 2026 SafeNexG Innovation. All rights reserved.</span><span>Privacy Policy&nbsp;&nbsp;|&nbsp;&nbsp;Terms</span></div></footer>}
